In [7]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
total=np.sum(arr1)
sum_column=np.sum(arr1,axis=0)
sum_row=np.sum(arr1,axis=1)
print("sum of all elements of the array: ", total)
print("sum of each column: ",sum_column)
print("sum of each row: ", sum_row)


sum of all elements of the array:  21
sum of each column:  [5 7 9]
sum of each row:  [ 6 15]


In [13]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
number=5
greater=arr2[arr2>number]
less=arr2[arr2<=number]
print("numbers greater than 5: ", greater)
print("numbers less than or equal to 5: ", less)

numbers greater than 5:  [6 7 8 9]
numbers less than or equal to 5:  [1 2 3 4 5]


In [2]:
import numpy as np
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4=np.array([[11,12,13],[14,15,16],[17,18,19]])
arr5=np.array([[21,22,23],[24,25,26],[27,28,29]])
arr6=np.concatenate((arr3,arr4,arr5),axis=0)
arr7=np.concatenate((arr3,arr4,arr5),axis=1)
print("arrays concatenated vertically: ", arr6)
print("arrays concatenated horizontally: ", arr7)

arrays concatenated vertically:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
arrays concatenated horizontally:  [[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]
